GymManagement(PL)/Controllers/MemberShipController.cs
using GymManagementBLL.Services.Interfaces;
using GymManagementBLL.Services.ServicesImplementation;
using GymManagementBLL.ViewModels.MemberShipViewModels;
using GymManagementDAL.Entities;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace GymManagementPL.Controllers
{
    public class MemberShipController : Controller
    {
        private readonly IMemberShipService _memberShipService;

        public MemberShipController(IMemberShipService memberShipService)
        {
            _memberShipService = memberShipService;
        }
        public ActionResult Index()
        {
            var memberShips = _memberShipService.GetAllMemberShips();
            return View(memberShips);
        }
        public ActionResult Create()
        {
            LoadDropDownLists();

            return View();
        }
        [HttpPost]
        public ActionResult Create(CreateMemberShipViewModel model)
        {
            if (!ModelState.IsValid)
            {
                LoadDropDownLists();
                return View(model);
            }
            bool Result = _memberShipService.CreateMemberShip(model);
            if (Result)
            {
                TempData["SuccessMessage"] = "Member Created Successfully";
            }
            else
            {
                TempData["ErrorMessage"] = "Failed To Create MemberShip";
            }

            return RedirectToAction(nameof(Index));

        }
        public ActionResult Cancle(int Id)
        {
            var Result = _memberShipService.DeleteMemberShip(Id);
            if (Result)
            {
                TempData["SuccessMessage"] = "Membership Cancled Successfully";
                return RedirectToAction(nameof(Index));
            }
            else
            {
                TempData["ErrorMessage"] = "Failed To Cancle Membership ";
                return RedirectToAction(nameof(Index));

            }

        }
        #region HelperMethods
        public void LoadDropDownLists()
        {
            var plans = _memberShipService.GetPlanForSelectListViewModels();
            ViewBag.Plans = new SelectList(plans, "Id", "Name");
            var members = _memberShipService.GetMemberForSelectListViewModels();
            ViewBag.Members = new SelectList(members, "Id", "Name");
        }
        #endregion

    }
}

GymManagement(PL)/Views/MemberShip/Create.cshtml
@model CreateMemberShipViewModel
@{
    ViewData["Title"] = "CreateMemberShip";
}


@if (TempData["SuccessMessage"] is not null)
{
    <div id="Alert" class="alert alert-success alert-dismissible fade show">
        <i class="bi bi-check-circle-fill me-2"></i>
        @TempData["SuccessMessage"]
        <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
    </div>
}

@if (TempData["ErrorMessage"] is not null)
{
    <div id="Alert" class="alert alert-danger alert-dismissible fade show">
        <i class="bi bi-exclamation-triangle-fill me-2"></i>
        @TempData["ErrorMessage"]
        <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
    </div>
}

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-header">
                    <h4 >CreateMemberShip</h4>
                </div>
                <div class="card-body">
                    <form asp-controller="MemberShip" asp-action="Create" method="post">

                        <div class="mb-3 text-dark">
                            <label asp-for="MemberId" class="form-label">Member</label>
                            <select asp-for="MemberId" asp-items="ViewBag.Members" class="form-select">
                                <option value="">-- Select Member --</option>
                            </select>
                        </div>

                        <div class="mb-3">
                            <label class="form-label">Plan</label>
                            <label asp-for="PlanId" class="form-label">Plan</label>
                            <select asp-for="PlanId" asp-items="ViewBag.Plans" class="form-select">
                                <option value="">-- Select Plans --</option>
                            </select>
                        </div>

                        <div class="mb-3">
                            <button type="submit" class="btn bg-primary-color">Create Membership</button>
                            <a asp-action="Index" class="btn btn-secondary">Cancel</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<script src="../js/jquery.validate.min.js"></script>
<script src="../js/jquery.validate.unobtrusive.min.js"></script>
<script>
    document.addEventListener("DOMContentLoaded", function () {
        const alertBox = document.getElementById("Alert");
        if (alertBox) {
            setTimeout(() => {
                alertBox.style.transition = "opacity 0.5s ease";
                alertBox.style.opacity = "0";
                setTimeout(() => alertBox.remove(), 500);
            }, 1500);
        }
    });
</script>

GymManagement(PL)/Views/MemberShip/Index.cshtml
@model IEnumerable<MemberShipViewModel>
@{
    ViewData["Title"] = "Active Memberships";
}

<div class="container-fluid page">
    <header class="btn-on-yellow  text-white rounded-3 p-4 shadow-sm mt-5 mb-4">
        <div class="d-flex justify-content-between align-items-center">
            <div>
                <h2 class="mb-1 fw-semibold text-dark ">Active Memberships</h2>
                <p class="mb-0 text-light opacity-75 text-dark">Members That have Active Plans</p>
            </div>
            <div class="col text-end ">
                <a asp-action="Create" class="btn bg-primary-color">
                    <i class="fas fa-plus"></i> New Membership
                </a>
            </div>
        </div>
    </header>

    @if (TempData["SuccessMessage"] is not null)
    {
        <div id="Alert" class="alert alert-success alert-dismissible fade show">
            <i class="bi bi-check-circle-fill me-2"></i>
            @TempData["SuccessMessage"]
            <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
        </div>
    }

    @if (TempData["ErrorMessage"] is not null)
    {
        <div id="Alert" class="alert alert-danger alert-dismissible fade show">
            <i class="bi bi-exclamation-triangle-fill me-2"></i>
            @TempData["ErrorMessage"]
            <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
        </div>
    }

    <div class="card">
        <div class="card">
            @if (Model is not null && Model.Any())
            {
                <table class="table table-borderless bg-black">
                    <thead>
                    <tr>
                        <th>Member</th>
                        <th>Plan</th>
                        <th>Start Date</th>
                        <th>End Date</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    
                @foreach (var item in Model)
                    {
                      <tr>
                        <td>@item.MemberName</td>
                        <td>@item.PlanName</td>
                        <td>@item.StartDate</td>
                        <td>@item.EndDate</td>
                        <td>
                            <div class="d-flex gap-1">
                                <form method="post" asp-action="Cancle" href="membership/cancel" class="m-0">
                                    <input type="hidden" name="id" value="@item.MemberId" />
                                    <button type="submit" class="btn btn-sm btn-fill">
                                        <i class="fas fa-times "></i> Cancel
                                    </button>
                                </form>
                            </div>
                        </td>
                    </tr>
                    }
                </tbody>
            </table>
            }
            else
            {
            <div class="text-center py-5">
                <i class="bi bi-person-workspace display-1 text-muted"></i>
                <h4 class="mt-3 text-muted">No Active Memberships Available</h4>
            </div>
            }
        </div>
    </div>
</div>